// admin/src/components/content/CollectionHeader.vue
<template>
  <div class="collection-head">
    <h3>{{ title }}</h3><a-tooltip :title="addHint">
      <a-button
        type="primary"
        :disabled="addDisabled"
        @click="$emit('add')"
      >
        新增
      </a-button>
    </a-tooltip>
  </div>
</template>
<script setup lang="ts">withDefaults(defineProps<{ title: string; addDisabled?: boolean; addHint?: string }>(), { addDisabled: false, addHint: '' }); defineEmits<{ add: [] }>()</script>
<style scoped>.collection-head{display:flex;align-items:center;justify-content:space-between;margin:20px 0 12px}.collection-head h3{margin:0}</style>

// admin/src/components/content/CollectionHeader.tsx
import { Button, Tooltip } from 'antd'
import styles from './CollectionHeader.module.scss'

export interface CollectionHeaderProps {
  title: string
  addDisabled?: boolean
  addHint?: string
  onAdd: () => void
}

/** 集合区块标题行：左侧标题，右侧「新增」按钮（带提示） */
export const CollectionHeader = ({
  title,
  addDisabled = false,
  addHint = '',
  onAdd,
}: CollectionHeaderProps) => (
  <div className={styles['collection-head']}>
    <h3>{title}</h3>
    <Tooltip title={addHint}>
      <Button type="primary" disabled={addDisabled} onClick={onAdd}>新增</Button>
    </Tooltip>
  </div>
)
