// admin/src/pages/system/FileManage.tsx
/**
 * 文件资源管理：分页列表、目录筛选、多文件上传、删除前引用检查、复制预签名访问地址。
 */
import { useCallback, useEffect, useRef, useState, type ChangeEvent } from 'react'
import { App, Alert, Button, Card, Col, Image, Input, Modal, Row, Select, Space, Table, Tag } from 'antd'
import type { TablePaginationConfig, TableProps } from 'antd'
import {
  DatabaseOutlined,
  FileImageOutlined,
  FileOutlined,
  ReloadOutlined,
  SearchOutlined,
  UploadOutlined
} from '@ant-design/icons'
import type { FileReference, FileResource, ResourceDirectory } from '@/types'
import { deleteFileApi, getFileAccessUrlApi, getFileListApi, getFileReferencesApi, uploadFileApi } from '@/api/file'
import styles from './FileManage.module.scss'

const imageTypes = 'image/png,image/jpeg,image/webp,image/gif,image/svg+xml'
const acceptedTypes = imageTypes

const filterDirectoryOptions: Array<{ value: ResourceDirectory, label: string }> = [
  { value: 'hero', label: '首页图片 hero' },
  { value: 'icon', label: '图标 icon' },
  { value: 'hobbies', label: '爱好 hobbies' },
  { value: 'footstep', label: '足迹 footstep' },
  { value: 'mylab-post', label: 'MyLab 封面' }
]
const uploadDirectoryOptions = filterDirectoryOptions

const isImage = (file: FileResource) => file.mimeType.startsWith('image/')
const getFileTypeLabel = (type: string) => type.startsWith('image/') ? '图片' : type
const formatFileSize = (size: number) => {
  if (size < 1024) return `${size} B`
  if (size < 1024 ** 2) return `${(size / 1024).toFixed(1)} KB`
  if (size < 1024 ** 3) return `${(size / 1024 ** 2).toFixed(1)} MB`
  return `${(size / 1024 ** 3).toFixed(2)} GB`
}
const formatTime = (value: string) => value ? new Date(value).toLocaleString('zh-CN') : '-'
const directoryLabel = (directory?: ResourceDirectory) =>
  filterDirectoryOptions.find(item => item.value === directory)?.label || '未分类资源'
const moduleLabel = (moduleKey: string) => ({
  home: '首页图片',
  about: '关于我',
  skills: '技术栈',
  footprints: '足迹',
  hobbies: '爱好',
  vibe: 'Vibe Coding',
  mylab: 'MyLab'
} as Record<string, string>)[moduleKey] || moduleKey
const versionStateLabel = (state: string) => ({
  DRAFT: '草稿',
  PUBLISHED: '已发布',
  ARCHIVED: '已归档',
  OFFLINE: '已下线'
} as Record<string, string>)[state] || state

const FileManage = () => {
  const { message } = App.useApp()
  const [files, setFiles] = useState<FileResource[]>([])
  const [loading, setLoading] = useState(false)
  const [searchKeyword, setSearchKeyword] = useState('')
  const [filterDirectory, setFilterDirectory] = useState<ResourceDirectory>()
  const [uploadDirectory, setUploadDirectory] = useState<ResourceDirectory>('hero')
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(20)
  const [total, setTotal] = useState(0)
  const [deleteTarget, setDeleteTarget] = useState<FileResource | null>(null)
  const [deleteReferences, setDeleteReferences] = useState<FileReference[]>([])
  const [deleting, setDeleting] = useState(false)

  // 加载列表：分页参数显式传入，避免 setState 后读到旧值
  const loadData = useCallback(async (nextPage: number, nextPageSize: number, directory?: ResourceDirectory) => {
    setLoading(true)
    try {
      const result = await getFileListApi(nextPage, nextPageSize, directory)
      setFiles(result.records)
      setTotal(result.total)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void loadData(1, 20)
  }, [loadData])

  const currentPageSizeText = formatFileSize(files.reduce((sum, file) => sum + file.size, 0))
  const keyword = searchKeyword.trim().toLowerCase()
  const filteredFiles = files.filter(file =>
    !keyword || file.originalName.toLowerCase().includes(keyword) || file.objectKey.toLowerCase().includes(keyword)
  )

  const handleTableChange = (value: TablePaginationConfig) => {
    const nextPage = value.current || 1
    const nextPageSize = value.pageSize || 20
    setPage(nextPage)
    setPageSize(nextPageSize)
    void loadData(nextPage, nextPageSize, filterDirectory)
  }

  const onDirectoryFilterChange = (value?: ResourceDirectory) => {
    setFilterDirectory(value)
    setPage(1)
    void loadData(1, pageSize, value)
  }

  const triggerUpload = () => fileInputRef.current?.click()
  const handleUpload = async (event: ChangeEvent<HTMLInputElement>) => {
    const selected = event.target.files
    if (!selected?.length) return
    setLoading(true)
    try {
      await Promise.all(Array.from(selected).map(file => uploadFileApi(file, uploadDirectory)))
      message.success(`已上传 ${selected.length} 个文件`)
      setPage(1)
      await loadData(1, pageSize, filterDirectory)
    } finally {
      setLoading(false)
      if (fileInputRef.current) fileInputRef.current.value = ''
    }
  }

  const copyAccessUrl = async (file: FileResource) => {
    const url = file.url || await getFileAccessUrlApi(file.id)
    await navigator.clipboard.writeText(url)
    message.success('访问地址已复制，有效期以接口返回策略为准')
  }

  // 删除前先查引用，再打开受控确认弹窗；仍被引用时禁用删除按钮
  const handleDelete = async (file: FileResource) => {
    const references = await getFileReferencesApi(file.id)
    setDeleteReferences(references)
    setDeleteTarget(file)
  }

  const confirmDelete = async () => {
    if (!deleteTarget) return
    setDeleting(true)
    try {
      await deleteFileApi(deleteTarget.id)
      // 删空当前页时回退一页
      const nextPage = files.length === 1 && page > 1 ? page - 1 : page
      setPage(nextPage)
      message.success('文件删除任务已提交')
      setDeleteTarget(null)
      await loadData(nextPage, pageSize, filterDirectory)
    } finally {
      setDeleting(false)
    }
  }

  const columns: TableProps<FileResource>['columns'] = [
    {
      title: '预览',
      key: 'preview',
      width: 80,
      align: 'center',
      render: (_, record) => isImage(record) && record.url ? (
        <Image src={record.url} width={50} height={50} className={styles['file-thumb']} />
      ) : (
        <div className={styles['file-icon']}>
          {record.mimeType.startsWith('image/') ? <FileImageOutlined /> : <FileOutlined />}
        </div>
      )
    },
    {
      title: '文件',
      key: 'name',
      render: (_, record) => (
        <div className={styles['file-name']}>
          <strong>{record.originalName || '未命名文件'}</strong>
          <span>{record.objectKey}</span>
        </div>
      )
    },
    {
      title: 'MIME',
      key: 'mimeType',
      width: 150,
      align: 'center',
      render: (_, record) => (
        <Tag color={record.mimeType.startsWith('image/') ? 'success' : 'default'}>
          {getFileTypeLabel(record.mimeType)}
        </Tag>
      )
    },
    {
      title: '目录',
      key: 'directory',
      width: 130,
      align: 'center',
      render: (_, record) => <Tag>{directoryLabel(record.directory)}</Tag>
    },
    {
      title: '大小',
      key: 'size',
      width: 110,
      align: 'right',
      render: (_, record) => formatFileSize(record.size)
    },
    { title: '存储桶', dataIndex: 'bucket', key: 'bucket', width: 130 },
    {
      title: '上传时间',
      key: 'createdAt',
      width: 180,
      render: (_, record) => formatTime(record.createdAt)
    },
    {
      title: '操作',
      key: 'actions',
      width: 210,
      align: 'center',
      render: (_, record) => (
        <Space>
          <Button type="link" size="small" onClick={() => copyAccessUrl(record)}>
            复制访问地址
          </Button>
          <Button type="link" danger size="small" onClick={() => handleDelete(record)}>
            删除
          </Button>
        </Space>
      )
    }
  ]

  return (
    <div className={styles['file-manage']}>
      <Card
        variant="borderless"
        title={(
          <div className={styles['card-header']}>
            <span>文件资源</span>
            <div className={styles['header-actions']}>
              <Input
                value={searchKeyword}
                placeholder="筛选当前页文件名"
                allowClear
                style={{ width: 210 }}
                prefix={<SearchOutlined />}
                onChange={event => setSearchKeyword(event.target.value)}
              />
              <Select
                value={filterDirectory}
                placeholder="筛选 OSS 目录"
                allowClear
                style={{ width: 150 }}
                options={filterDirectoryOptions}
                onChange={onDirectoryFilterChange}
              />
              <Select
                value={uploadDirectory}
                style={{ width: 150 }}
                options={uploadDirectoryOptions}
                aria-label="上传目标目录"
                onChange={setUploadDirectory}
              />
              <Button type="primary" icon={<UploadOutlined />} onClick={triggerUpload}>
                上传文件
              </Button>
              <input
                ref={fileInputRef}
                type="file"
                multiple
                accept={acceptedTypes}
                className={styles['hidden-input']}
                onChange={handleUpload}
              />
              <Button icon={<ReloadOutlined />} onClick={() => void loadData(page, pageSize, filterDirectory)}>
                刷新
              </Button>
            </div>
          </div>
        )}
      >
        <Alert
          type="info"
          showIcon
          className={styles['file-tip']}
          message="删除前后端会检查所有草稿、线上和历史版本，仍被引用的资源不可删除。"
        />

        <Row gutter={16} className={styles['stat-row']}>
          <Col xs={24} sm={12}>
            <div className={styles['stat-item']}>
              <FileOutlined className={`${styles['stat-icon']} ${styles['icon-blue']}`} />
              <div>
                <div className={styles['stat-value']}>{total}</div>
                <div className={styles['stat-label']}>资源总数</div>
              </div>
            </div>
          </Col>
          <Col xs={24} sm={12}>
            <div className={styles['stat-item']}>
              <DatabaseOutlined className={`${styles['stat-icon']} ${styles['icon-orange']}`} />
              <div>
                <div className={styles['stat-value']}>{currentPageSizeText}</div>
                <div className={styles['stat-label']}>当前页占用</div>
              </div>
            </div>
          </Col>
        </Row>

        <Table<FileResource>
          dataSource={filteredFiles}
          columns={columns}
          loading={loading}
          rowKey="id"
          pagination={{
            current: page,
            pageSize,
            total,
            showSizeChanger: true,
            showTotal: value => `共 ${value} 个资源`
          }}
          onChange={handleTableChange}
        />
      </Card>

      <Modal
        open={!!deleteTarget}
        title={`确认删除「${deleteTarget ? deleteTarget.originalName || deleteTarget.objectKey : ''}」？`}
        okText="删除"
        okButtonProps={{ danger: true, disabled: deleteReferences.length > 0 }}
        confirmLoading={deleting}
        onOk={confirmDelete}
        onCancel={() => setDeleteTarget(null)}
      >
        {deleteReferences.length ? (
          <div>
            <p>该资源仍被以下内容版本引用，解除引用后才可删除：</p>
            <ul style={{ margin: '8px 0 0', paddingLeft: 18 }}>
              {deleteReferences.map((ref, index) => (
                <li key={index}>
                  {`${moduleLabel(ref.moduleKey)} · v${ref.versionNo}（${versionStateLabel(ref.state)}）· ${ref.usage}`}
                </li>
              ))}
            </ul>
          </div>
        ) : (
          '未被任何内容版本引用，可安全删除。'
        )}
      </Modal>
    </div>
  )
}

export default FileManage

// admin/src/views/system/FileManage.vue
<template>
  <div class="file-manage">
    <a-card :bordered="false">
      <template #title>
        <div class="card-header">
          <span>文件资源</span>
          <div class="header-actions">
            <a-input
              v-model:value="searchKeyword"
              placeholder="筛选当前页文件名"
              allow-clear
              style="width: 210px"
            >
              <template #prefix>
                <SearchOutlined />
              </template>
            </a-input>
            <a-select
              v-model:value="filterDirectory"
              placeholder="筛选 OSS 目录"
              allow-clear
              style="width: 150px"
              :options="filterDirectoryOptions"
              @change="onDirectoryFilterChange"
            />
            <a-select
              v-model:value="uploadDirectory"
              style="width: 150px"
              :options="uploadDirectoryOptions"
              aria-label="上传目标目录"
            />
            <a-button
              type="primary"
              @click="triggerUpload"
            >
              <template #icon>
                <UploadOutlined />
              </template>
              上传文件
            </a-button>
            <input
              ref="fileInputRef"
              type="file"
              multiple
              :accept="acceptedTypes"
              class="hidden-input"
              @change="handleUpload"
            >
            <a-button @click="loadData">
              <template #icon>
                <ReloadOutlined />
              </template>刷新
            </a-button>
          </div>
        </div>
      </template>

      <a-alert
        type="info"
        show-icon
        class="file-tip"
        message="删除前后端会检查所有草稿、线上和历史版本，仍被引用的资源不可删除。"
      />

      <a-row
        :gutter="16"
        class="stat-row"
      >
        <a-col
          :xs="24"
          :sm="12"
        >
          <div class="stat-item">
            <FileOutlined class="stat-icon icon-blue" />
            <div>
              <div class="stat-value">
                {{ total }}
              </div><div class="stat-label">
                资源总数
              </div>
            </div>
          </div>
        </a-col>
        <a-col
          :xs="24"
          :sm="12"
        >
          <div class="stat-item">
            <DatabaseOutlined class="stat-icon icon-orange" />
            <div>
              <div class="stat-value">
                {{ currentPageSizeText }}
              </div><div class="stat-label">
                当前页占用
              </div>
            </div>
          </div>
        </a-col>
      </a-row>

      <a-table
        :data-source="filteredFiles"
        :columns="columns"
        :loading="loading"
        row-key="id"
        :pagination="pagination"
        @change="handleTableChange"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.key === 'preview'">
            <a-image
              v-if="isImage(record) && record.url"
              :src="record.url"
              :width="50"
              :height="50"
              class="file-thumb"
            />
            <div
              v-else
              class="file-icon"
            >
              <component :is="getFileIcon(record.mimeType)" />
            </div>
          </template>
          <template v-else-if="column.key === 'name'">
            <div class="file-name">
              <strong>{{ record.originalName || '未命名文件' }}</strong>
              <span>{{ record.objectKey }}</span>
            </div>
          </template>
          <template v-else-if="column.key === 'mimeType'">
            <a-tag :color="record.mimeType.startsWith('image/') ? 'success' : 'default'">
              {{ getFileTypeLabel(record.mimeType) }}
            </a-tag>
          </template>
          <template v-else-if="column.key === 'directory'">
            <a-tag>{{ directoryLabel(record.directory) }}</a-tag>
          </template>
          <template v-else-if="column.key === 'size'">
            {{ formatFileSize(record.size) }}
          </template>
          <template v-else-if="column.key === 'createdAt'">
            {{ formatTime(record.createdAt) }}
          </template>
          <template v-else-if="column.key === 'actions'">
            <a-space>
              <a-button
                type="link"
                size="small"
                @click="copyAccessUrl(record)"
              >
                复制访问地址
              </a-button>
              <a-button
                type="link"
                danger
                size="small"
                @click="handleDelete(record)"
              >
                删除
              </a-button>
            </a-space>
          </template>
        </template>
      </a-table>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { computed, h, onMounted, ref } from 'vue'
import { message, Modal } from 'ant-design-vue'
import type { TablePaginationConfig } from 'ant-design-vue'
import {
  DatabaseOutlined,
  FileImageOutlined,
  FileOutlined,
  ReloadOutlined,
  SearchOutlined,
  UploadOutlined
} from '@ant-design/icons-vue'
import type { FileResource, ResourceDirectory } from '@/types'
import { deleteFileApi, getFileAccessUrlApi, getFileListApi, getFileReferencesApi, uploadFileApi } from '@/api/file'

const imageTypes = 'image/png,image/jpeg,image/webp,image/gif,image/svg+xml'
const files = ref<FileResource[]>([])
const loading = ref(false)
const searchKeyword = ref('')
const filterDirectory = ref<ResourceDirectory>()
const uploadDirectory = ref<ResourceDirectory>('hero')
const fileInputRef = ref<HTMLInputElement>()
const page = ref(1)
const pageSize = ref(20)
const total = ref(0)
const filterDirectoryOptions: Array<{ value: ResourceDirectory, label: string }> = [
  { value: 'hero', label: '首页图片 hero' },
  { value: 'icon', label: '图标 icon' },
  { value: 'hobbies', label: '爱好 hobbies' },
  { value: 'footstep', label: '足迹 footstep' },
  { value: 'mylab-post', label: 'MyLab 封面' }
]
const uploadDirectoryOptions = filterDirectoryOptions
const acceptedTypes = imageTypes

const currentPageSizeText = computed(() => formatFileSize(files.value.reduce((sum, file) => sum + file.size, 0)))
const pagination = computed<TablePaginationConfig>(() => ({
  current: page.value,
  pageSize: pageSize.value,
  total: total.value,
  showSizeChanger: true,
  showTotal: value => `共 ${value} 个资源`
}))
const filteredFiles = computed(() => files.value.filter(file => {
  const keyword = searchKeyword.value.trim().toLowerCase()
  const matchesKeyword = !keyword || file.originalName.toLowerCase().includes(keyword) || file.objectKey.toLowerCase().includes(keyword)
  return matchesKeyword
}))

const columns = [
  { title: '预览', key: 'preview', width: 80, align: 'center' as const },
  { title: '文件', key: 'name', minWidth: 260 },
  { title: 'MIME', key: 'mimeType', width: 150, align: 'center' as const },
  { title: '目录', key: 'directory', width: 130, align: 'center' as const },
  { title: '大小', key: 'size', width: 110, align: 'right' as const },
  { title: '存储桶', dataIndex: 'bucket', key: 'bucket', width: 130 },
  { title: '上传时间', key: 'createdAt', width: 180 },
  { title: '操作', key: 'actions', width: 210, align: 'center' as const }
]

const loadData = async () => {
  loading.value = true
  try {
    const result = await getFileListApi(page.value, pageSize.value, filterDirectory.value)
    files.value = result.records
    total.value = result.total
  } finally {
    loading.value = false
  }
}

const handleTableChange = (value: TablePaginationConfig) => {
  page.value = value.current || 1
  pageSize.value = value.pageSize || 20
  loadData()
}

const onDirectoryFilterChange = () => {
  page.value = 1
  loadData()
}

const isImage = (file: FileResource) => file.mimeType.startsWith('image/')
const getFileIcon = (type: string) => type.startsWith('image/') ? FileImageOutlined : FileOutlined
const getFileTypeLabel = (type: string) => type.startsWith('image/') ? '图片' : type
const formatFileSize = (size: number) => {
  if (size < 1024) return `${size} B`
  if (size < 1024 ** 2) return `${(size / 1024).toFixed(1)} KB`
  if (size < 1024 ** 3) return `${(size / 1024 ** 2).toFixed(1)} MB`
  return `${(size / 1024 ** 3).toFixed(2)} GB`
}
const formatTime = (value: string) => value ? new Date(value).toLocaleString('zh-CN') : '-'
const directoryLabel = (directory?: ResourceDirectory) => filterDirectoryOptions.find(item => item.value === directory)?.label || '未分类资源'
const moduleLabel = (moduleKey: string) => ({
  home: '首页图片',
  about: '关于我',
  skills: '技术栈',
  footprints: '足迹',
  hobbies: '爱好',
  vibe: 'Vibe Coding',
  mylab: 'MyLab'
} as Record<string, string>)[moduleKey] || moduleKey
const versionStateLabel = (state: string) => ({
  DRAFT: '草稿',
  PUBLISHED: '已发布',
  ARCHIVED: '已归档',
  OFFLINE: '已下线'
} as Record<string, string>)[state] || state

const triggerUpload = () => fileInputRef.value?.click()
const handleUpload = async (event: Event) => {
  const selected = (event.target as HTMLInputElement).files
  if (!selected?.length) return
  loading.value = true
  try {
    await Promise.all(Array.from(selected).map(file => uploadFileApi(file, uploadDirectory.value)))
    message.success(`已上传 ${selected.length} 个文件`)
    page.value = 1
    await loadData()
  } finally {
    loading.value = false
    if (fileInputRef.value) fileInputRef.value.value = ''
  }
}

const copyAccessUrl = async (file: FileResource) => {
  const url = file.url || await getFileAccessUrlApi(file.id)
  await navigator.clipboard.writeText(url)
  message.success('访问地址已复制，有效期以接口返回策略为准')
}

const handleDelete = async (file: FileResource) => {
  const references = await getFileReferencesApi(file.id)
  Modal.confirm({
    title: `确认删除「${file.originalName || file.objectKey}」？`,
    content: references.length
      ? h('div', [
          h('p', '该资源仍被以下内容版本引用，解除引用后才可删除：'),
          h('ul', { style: 'margin: 8px 0 0; padding-left: 18px;' }, references.map(ref =>
            h('li', `${moduleLabel(ref.moduleKey)} · v${ref.versionNo}（${versionStateLabel(ref.state)}）· ${ref.usage}`)
          ))
        ])
      : '未被任何内容版本引用，可安全删除。',
    okText: '删除',
    okButtonProps: { danger: true, disabled: references.length > 0 },
    onOk: async () => {
      await deleteFileApi(file.id)
      if (files.value.length === 1 && page.value > 1) page.value--
      message.success('文件删除任务已提交')
      await loadData()
    }
  })
}

onMounted(loadData)
</script>

<style scoped lang="scss">
.card-header { display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 12px; }
.header-actions { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
.hidden-input { display: none; }
.file-tip, .stat-row { margin-bottom: 16px; }
.stat-item { display: flex; align-items: center; gap: 12px; padding: 16px; background: #fafafa; border-radius: 8px; }
.stat-icon { font-size: 32px; }
.icon-blue { color: #1677ff; }
.icon-orange { color: #faad14; }
.stat-value { font-size: 22px; font-weight: 600; line-height: 1.2; }
.stat-label { margin-top: 2px; font-size: 13px; color: #8c8c8c; }
.file-thumb { border-radius: 4px; }
.file-icon { width: 50px; height: 50px; border-radius: 4px; background: #fafafa; display: flex; align-items: center; justify-content: center; font-size: 24px; color: #8c8c8c; }
.file-name { display: flex; flex-direction: column; gap: 3px; }
.file-name span { color: #8c8c8c; font-size: 12px; word-break: break-all; }
</style>
