// myblog/src/components/ui/RevealOnScroll.tsx
/* 滚动入场/退场容器：进入视口播放入场动画，delay 控制入场延迟 */
import type { ReactNode } from 'react'
import { useScrollReveal } from '@/hooks/useScrollReveal'
import styles from './RevealOnScroll.module.css'

interface RevealOnScrollProps {
  /** 入场延迟档位 0~4（每档 0.1s） */
  delay?: 0 | 1 | 2 | 3 | 4
  /** 追加到根 div 的类名（等价 Vue 中 class 落到组件根节点的透传） */
  className?: string
  children: ReactNode
}

export function RevealOnScroll({ delay = 0, className, children }: RevealOnScrollProps) {
  const { target: targetRef, isVisible } = useScrollReveal()

  const delayClass = delay > 0 ? styles[`reveal-delay-${Math.min(delay, 4)}`] : ''
  const rootClass = `${styles.reveal}${isVisible ? ` ${styles.visible}` : ''}${delayClass ? ` ${delayClass}` : ''}${className ? ` ${className}` : ''}`

  return (
    <div ref={targetRef} className={rootClass}>
      {children}
    </div>
  )
}

// myblog/src/components/ui/RevealOnScroll.vue
<template>
  <div 
    ref="targetRef"
    class="reveal"
    :class="[{ visible: isVisible }, delayClass]"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useScrollReveal } from '@/composables/useScrollReveal'

const props = withDefaults(defineProps<{
  delay?: number
}>(), {
  delay: 0
})

const { target: targetRef, isVisible } = useScrollReveal()

defineExpose({ targetRef })

const delayClass = computed(() => {
  if (props.delay > 0) {
    return `reveal-delay-${Math.min(props.delay, 4)}`
  }
  return ''
})
</script>

<style scoped>
.reveal {
  opacity: 0;
  transform: translateY(32px);
  transition: opacity 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94),
              transform 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94);
}

.reveal.visible {
  opacity: 1;
  transform: translateY(0);
}

.reveal-delay-1 { transition-delay: 0.1s; }
.reveal-delay-2 { transition-delay: 0.2s; }
.reveal-delay-3 { transition-delay: 0.3s; }
.reveal-delay-4 { transition-delay: 0.4s; }
</style>
