// admin/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="login-card">
      <div class="login-header">
        <img
          src="/favicon.svg"
          alt="logo"
          class="login-logo"
        >
        <h1 class="login-title">
          MyBlog
        </h1>
        <p class="login-subtitle">
          管理后台
        </p>
      </div>

      <a-form
        ref="formRef"
        :model="form"
        :rules="rules"
        class="login-form"
        @finish="handleLogin"
      >
        <a-form-item name="username">
          <a-input
            v-model:value="form.username"
            placeholder="请输入用户名"
            size="large"
            allow-clear
          >
            <template #prefix>
              <UserOutlined />
            </template>
          </a-input>
        </a-form-item>

        <a-form-item name="password">
          <a-input-password
            v-model:value="form.password"
            placeholder="请输入密码"
            size="large"
            allow-clear
            @press-enter="handleLogin"
          >
            <template #prefix>
              <LockOutlined />
            </template>
          </a-input-password>
        </a-form-item>

        <a-form-item>
          <a-button
            type="primary"
            size="large"
            :loading="loading"
            html-type="submit"
            block
          >
            {{ loading ? '登录中...' : '登 录' }}
          </a-button>
        </a-form-item>
      </a-form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { message } from 'ant-design-vue'
import { UserOutlined, LockOutlined } from '@ant-design/icons-vue'
import type { Rule } from 'ant-design-vue/es/form'
import { useAuth } from '@/composables/useAuth'
import { loginApi } from '@/api/auth'

const router = useRouter()
const route = useRoute()
const { login } = useAuth()

const formRef = ref()
const loading = ref(false)

const form = reactive({
  username: '',
  password: ''
})

const rules: Record<string, Rule[]> = {
  username: [
    { required: true, message: '请输入用户名', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' },
    { min: 8, max: 64, message: '密码长度为 8～64 位', trigger: 'blur' }
  ]
}

const handleLogin = async () => {
  if (!formRef.value) return

  try {
    await formRef.value.validate()
    loading.value = true

    const { token, user } = await loginApi(form.username, form.password)
    login(token, user)

    message.success('登录成功')

    const redirect = (route.query.redirect as string) || '/dashboard'
    router.push(redirect)
  } catch (error: unknown) {
    if (typeof error === 'object' && error !== null && 'errorFields' in error) {
      // 表单校验失败
      return
    }
  } finally {
    loading.value = false
  }
}
</script>

<style scoped lang="scss">
.login-container {
  width: 100%;
  height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-card {
  width: 400px;
  padding: 40px;
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.15);
}

.login-header {
  text-align: center;
  margin-bottom: 32px;
}

.login-logo {
  width: 56px;
  height: 56px;
  margin-bottom: 16px;
}

.login-title {
  font-size: 28px;
  font-weight: 600;
  color: #1f1f1f;
  margin: 0 0 4px;
}

.login-subtitle {
  font-size: 14px;
  color: #8c8c8c;
  margin: 0;
}

.login-form {
  :deep(.ant-form-item) {
    margin-bottom: 24px;
  }
}

</style>

// admin/src/pages/Login.tsx
import { useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { App, Button, Form, Input } from 'antd'
import type { Rule } from 'antd/es/form'
import { LockOutlined, UserOutlined } from '@ant-design/icons'
import { useAuthStore } from '@/stores/authStore'
import { loginApi } from '@/api/auth'
import styles from './Login.module.scss'

/** 登录表单字段 */
interface LoginFormValues {
  username: string
  password: string
}

// 校验规则与旧版保持一致（密码 8~64 位）
const rules: Record<keyof LoginFormValues, Rule[]> = {
  username: [{ required: true, message: '请输入用户名' }],
  password: [
    { required: true, message: '请输入密码' },
    { min: 8, max: 64, message: '密码长度为 8～64 位' }
  ]
}

/** 登录页 */
const Login = () => {
  const { message } = App.useApp()
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const login = useAuthStore((s) => s.login)
  const [form] = Form.useForm<LoginFormValues>()
  const [loading, setLoading] = useState(false)

  // 表单校验通过后执行登录，成功后按 URL query 的 redirect 回跳
  const handleLogin = async (values: LoginFormValues) => {
    setLoading(true)
    try {
      const { token, user } = await loginApi(values.username, values.password)
      login(token, user)
      message.success('登录成功')
      navigate(searchParams.get('redirect') || '/dashboard')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className={styles['login-container']}>
      <div className={styles['login-card']}>
        <div className={styles['login-header']}>
          <img src="/favicon.svg" alt="logo" className={styles['login-logo']} />
          <h1 className={styles['login-title']}>MyBlog</h1>
          <p className={styles['login-subtitle']}>管理后台</p>
        </div>

        <Form form={form} className={styles['login-form']} onFinish={handleLogin}>
          <Form.Item name="username" rules={rules.username}>
            <Input placeholder="请输入用户名" size="large" allowClear prefix={<UserOutlined />} />
          </Form.Item>

          <Form.Item name="password" rules={rules.password}>
            <Input.Password
              placeholder="请输入密码"
              size="large"
              allowClear
              prefix={<LockOutlined />}
              onPressEnter={() => form.submit()}
            />
          </Form.Item>

          <Form.Item>
            <Button type="primary" size="large" loading={loading} htmlType="submit" block>
              {loading ? '登录中...' : '登 录'}
            </Button>
          </Form.Item>
        </Form>
      </div>
    </div>
  )
}

export default Login
